const { Schema, model }=require("mongoose");

const productSchema=new Schema({
    title:{
        type:String,
        required:true,
        minlength:5,
        maxlength:50
    },
    content:{
        type:String,
        required:true,
        minlength:15,
        maxlength:100
    },
    price:{
        type:Number,
        required:true
    },
    category:{
        type:String,
        required:true,
        enum:["Salad","Rolls","Deserts","Sandwich","Cake","PureVeg","Pasta","Noodles"]
    },
    image:{
        type:String,
        required:true
    },
    stock:{
        type:Number,
        required:true,
        min:0,
        max:1000
    },
    brand:{
        type:String,
        required:true,
        minlength:2,
        maxlength:50
    },
    ratings:{
        type:Number,
        default:0,
        min:0,
        max:5
    }
},{timestamps:true});
const Product=model("Product",productSchema);
module.exports=Product;